### ISSUE TITLE
Combat.md: To Hit (by Height) Table

### ISSUE THREAD

**Issue by cptmashek** [WizardSpire/ccarps#37]
This table needs a graphic as well.

**Comment by RobertTheMagnificent** [comment]
Does the art department have the data to put in the graphic?

**Comment by cptmashek** [comment]
I'll double-check and make sure!

**Comment by cptmashek** [comment]
Art department has received a list of all the data for this, #33, #34, #35, #36, and others not listed here.

**Comment by cptmashek** [comment]
#45 fixes #33, #34, #35, and #36
